### ISSUE TITLE
Addition of Courier/Deploy Contrib Resolvers

### ISSUE THREAD

**Issue by leekelleher** [umbraco-community/awesome-umbraco#24]
This is essential for any UmbracoCloud project.

**Comment by jamiepollock** [comment]
I was under the impression this came as a part of the Visual Studio project UAAS.cmd makes for you?

That doesn't mean it shouldn't be on the list though as you rightly say it's essential to people who used Umbraco Cloud and they may not have used the UAAS.cmd tool.

**Comment by leekelleher** [comment]
Thanks Jamie. I wasn't aware about it being added via `UAAS.cmd` ... I
haven't set up any of my own projects using it. I'll take a look.

**Comment by jamiepollock** [comment]
Paul Sterling did a talk about it at uWestFest. It looks pretty sweet, I think it's documented on Our and seems to be the preferred way of handling code which would live in a separate repo and solution outside the "deployment repo" which Umbraco Cloud uses.

That project's source code lives as a sub module in another repo.

**Comment by leekelleher** [comment]
Hmmm, I've just tried out the `UAAS.cmd` (which downloads the `Waasp.exe` file and set-up the VS solution). It doesn't install or reference the "Umbraco.Courier.Contrib" NuGet package.

Interestingly, on a side-note, it does install UmbracoForms for you.

**Comment by jamiepollock** [comment]
Ahh, I must have misheard or misunderstood that part then. :/

**Comment by leekelleher** [comment]
@jamiepollock Definitely wasn't trying to prove you wrong 😉; I was curious if they did supply it, which I think would be a good thing for them to do.

**Comment by leekelleher** [comment]
Closing this ticket off. Courier/Deploy resolvers added in #51 #53
