### ISSUE TITLE
Review entire list for Umbraco 9

### ISSUE THREAD

**Issue by robertjf** [umbraco-community/awesome-umbraco#64]
'nuf said ;)

Anyway, here's a starter list for Umbraco 9 (full disclosure - some of these are ours):

# Multi-targeting Umbraco 8 & 9
* OpenOrClosed: https://github.com/YourITGroup/OpenOrClosed
* Our.Umbraco.GMaps (release 2.0 imminent): https://github.com/ArnoldV/Our.Umbraco.GMaps
* MemberListView: https://github.com/YourITGroup/MemberListView
* Vendr*: https://vendr.net/
* Contentment: https://github.com/leekelleher/umbraco-contentment

# Umbraco 9 only
* Koben.Iconic (release 3.0 in the works and under testing for Umbraco 9 by Mario Lopez): https://github.com/KOBENDigital/Iconic

**Comment by CarlSargunar** [comment]
Any value in archiving off historic lists so there's an easier way of looking at past versions without trawling the git history?

Thinking about before any large scale changes are made

**Comment by leekelleher** [comment]
@CarlSargunar Absolutely, it's the main reason I'm asking if anyone is interesting in taking over the curation/maintenance of this list. 👍👍

**Comment by CarlSargunar** [comment]
This sort of feels like maybe it's one for DevRel? Maybe @warrenbuckley or @emmaburstow , or is there anyone else on the community side?

Or are there any names in the community to pick it up? I can help as part of a group if there's interest, but it's not one I want to take on solo

**Comment by leekelleher** [comment]
Thanks @CarlSargunar. @patrickdemooij9 has offered to help, I've given him maintainer rights access. 👍 

I agree a team would ease any potential burdens (or bottlenecks) on a solo maintainer, (well, that's me speaking from my own experience 😆).

**Comment by patrickdemooij9** [comment]
Some more packages that we can probably add (after this PR is done. https://github.com/umbraco-community/awesome-umbraco/pull/66)

SimpleRedirects - https://our.umbraco.com/packages/backoffice-extensions/simpleredirects/
InboundLinkErrors - https://our.umbraco.com/packages/website-utilities/inbound-link-errors/
Newsletter Studio - https://our.umbraco.com/packages/backoffice-extensions/newsletter-studio-the-email-studio/ (is licensed)
Diplo God Mode - https://our.umbraco.com/packages/developer-tools/diplo-god-mode/
Full Text Search - https://our.umbraco.com/packages/website-utilities/full-text-search-for-umbraco/
Backoffice Themes - https://our.umbraco.com/packages/backoffice-extensions/backoffice-themes/
Preflight - https://our.umbraco.com/packages/backoffice-extensions/preflight-content-health-checks-for-umbraco-8/

**Comment by emma-hq** [comment]
I'll take a look at this too! Thanks for flagging @CarlSargunar

**Comment by patrickdemooij9** [comment]
Adding a bunch of packages with this PR: https://github.com/umbraco-community/awesome-umbraco/pull/67.
Let me know if I am missing any!

**Comment by robertjf** [comment]
@patrickdemooij9 MetaMomentum: https://github.com/DigitalMomentum/MetaMomentum - Dual Targeting 8 & 9
Also, Our.Umbraco.GMaps: https://github.com/ArnoldV/Our.Umbraco.GMaps -  is release-ready with dual targeting 8 & 9 - just waiting on @arnoldv to release it to nuGet so hopefully won't be long.

 - will post more here as I come across them.

**Comment by patrickdemooij9** [comment]
Will close this now with the release of the v10 list, but if you still have packages for v9 then please make a PR for it!
